### ISSUE TITLE
Feature request: change opacity of mean/median point

### ISSUE THREAD

**Issue by boasvdp** [JoachimGoedhart/SuperPlotsOfData#2]
Thanks for the nice tool! I am using it a lot, but I think adding a slider to change the opacity/alpha of the summary statistic (mean/median) point might improve the tool even more.

I have some datasets where the mean point overlaps with other mean points. Currently, the best option would be to split replicates into separate subplots but there are situations where I'd rather not split into subplots.

I am not that well-versed in Shiny applications, otherwise I'd open a PR, but I did notice that to achieve a change in opacity of the summary stat point, an alpha argument might be added in https://github.com/JoachimGoedhart/SuperPlotsOfData/blob/master/app.R#L1218-L1222

Best wishes Boas

**Comment by JoachimGoedhart** [comment]
Dear Boas, thanks for the encouraging words and the suggestion. I have added a slide to change the alpha of the large dots, you can find a version for testing here: https://goedhart.shinyapps.io/SuperPlotsOfData/
Let me know what you think!

**Comment by boasvdp** [comment]
Hi Joachim, thanks a lot! This is exactly what I was looking for. Works really well :-)
