### ISSUE TITLE
Different number of replicates 

### ISSUE THREAD

**Issue by lida-R** [JoachimGoedhart/SuperPlotsOfData#6]
Hi there,

I really like your package. 
I was wondering if your tool can support the data when have different sample sizes (n) ? 
I tried it out and it worked but not sure if we need to calculate the weighted mean or weighted SD when have different sizes in replicates. 

Thank you,
Lid

**Comment by JoachimGoedhart** [comment]
Excellent question! The nice aspect of the Superplot is that actually shows the difference in n. There is also the option "Size reflects 'n'" in the app.
For valid statistical comparison, the sample size needs to be taken into account, but you'll need a multilevel model. In the app though, we use a simplified approach, averaging the technical replicates and using the averages as N. See for further details the original Superplots paper (https://doi.org/10.1083/jcb.202001064) and the SuperPlotsOfData paper (https://www.molbiolcell.org/doi/10.1091/mbc.E20-09-0583)
